services:
  backend:
    build: ./
    container_name: wms_container
    working_dir: /wms
    ports:
      - "8000:8010"
    command:
      ./commands/start_server_${MODE}.sh
    volumes:
      - ./src:/wms/src
      - ./commands:/wms/commands
      - static_content:/wms/src/static
      - media_content:/wms/src/media
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:17.5
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pg_admin:/var/lib/pgadmin
    depends_on:
      - postgres

  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: my_mongo_db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env

    depends_on:
      - mongo

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/wms/src/static
      - media_content:/wms/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  pg_data: { }
  pg_admin: { }
  mongo_data: { }
  static_content: { }
  media_content: { }
