services:
  backend:
    build: ./
    container_name: wms_container
    working_dir: /wms
    ports:
      - "8000:8010"
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/wms/src
      - ./commands:/wms/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pg_admin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pg_data: { }
  pg_admin: { }
