server {
    listen 80 default_server;
    listen 443 default_server;

    server_name wms;

    client_max_body_size 20M;

    location /static/ {
        alias /wms/src/staticfiles/;
    }

    location /media/ {
        alias /wms/src/media/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://backend:8010;
    }
}